name: Dependabot Auto-Merge
on: workflow_call

jobs:
  dependabot:
    name: Auto-Merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        # Only enable auto-merge if the PR is not a major version update
        # if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        # Requires that auto-merge is enabled for the repository
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
