on: 
  workflow_call:
    secrets:
      skills-network-bot-app-id:
        required: false
      skills-network-bot-private-key:
        required: false
      asoc-key:
        required: false 
      asoc-secret:
        required: false
jobs:
  scan:
    name: static analysis
    runs-on: ubuntu-latest
    steps:
    - name: No-Op
      run: |
        echo "This action is no longer in use. It has been replaced by the IBM Mend Bot."
